-- BhavishAI: Track free reports generated by Founder Members
-- Run in Supabase SQL Editor. Safe to run before or after deploy.
-- Without it, founder free-report generation still works (just no per-month
-- quota tracking — which is fine since default is unlimited).
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS is_founder_free BOOLEAN DEFAULT false;
