import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { previewLimiter } from "../../../lib/rate-limit.js";
import { generateFullReport } from "../../../lib/report-generation.js";

// Allow up to 60 seconds for full report generation on Vercel
export const maxDuration = 60;

// PHASE 2 — Full report, only called AFTER payment is verified.
// Report generation itself lives in lib/report-generation.js so the
// server-side payment webhook can reuse it without HTTP/rate-limit hops.
//
// The tier (essential / premium / master) is read from the DB row (set by
// verify-payment) — NOT trusted from the client — so section depth and
// guidance are server-authoritative. Master's deep-dive is generated by a
// separate endpoint (/api/generate-master-deep-dive).
export async function POST(request) {
  try {
    // Rate limiting — prevent abuse of expensive AI generation
    const rateCheck = await previewLimiter(request);
    if (!rateCheck.allowed) {
      return NextResponse.json({ error: rateCheck.error }, { status: 429 });
    }

    const {
      reportId,
      name,
      gender,
      dateOfBirth,
      timeOfBirth,
      placeOfBirth,
      chartData,
      personalQuestion,
    } = await request.json();

    if (!reportId || !name || !chartData) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // SECURITY: Verify payment was actually made before generating full report.
    // Prevents paywall bypass by directly calling this endpoint with chartData.
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    );

    const { data: report, error: dbError } = await supabase
      .from("reports")
      .select("payment_status, payment_id, plan_tier, guidance_months, has_12_month_guidance, deep_dive_focus")
      .eq("report_id", reportId)
      .single();

    if (dbError || !report) {
      return NextResponse.json({ error: "Report not found. Please try again." }, { status: 404 });
    }

    if (report.payment_status !== "paid") {
      return NextResponse.json({ error: "Payment required to generate full report." }, { status: 403 });
    }

    // Server-authoritative tier + guidance (from the paid DB row).
    const tier = ["essential", "premium", "master"].includes(report.plan_tier)
      ? report.plan_tier
      : "premium"; // legacy paid rows → full 20-section report
    const guidanceMonths =
      typeof report.guidance_months === "number"
        ? report.guidance_months
        : report.has_12_month_guidance
        ? 12
        : 0;
    const isMaster = tier === "master";

    // Generate via the shared library
    let reportData;
    try {
      reportData = await generateFullReport({
        name,
        gender,
        dateOfBirth,
        timeOfBirth,
        placeOfBirth,
        chartData,
        personalQuestion,
        tier,
        guidanceMonths,
      });
    } catch (genError) {
      return NextResponse.json({ error: genError.message || "Failed to generate report." }, { status: 500 });
    }

    // Persist the generated main report so the secure link / dashboard / deep-dive
    // all work off the DB (best-effort; the browser also keeps a copy).
    try {
      await supabase
        .from("reports")
        .update({
          summary: reportData.summary,
          sections: reportData.sections,
          report_status: "completed",
        })
        .eq("report_id", reportId);
    } catch (e) {
      console.error("Failed to persist generated report (non-critical):", e.message);
    }

    return NextResponse.json({
      reportId,
      summary: reportData.summary,
      sections: reportData.sections,
      tier,
      guidanceMonths,
      deepDive: isMaster,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error("Full report generation error:", error);
    return NextResponse.json({ error: "Failed to generate report. Please try again." }, { status: 500 });
  }
}
