import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { previewLimiter } from "../../../lib/rate-limit.js";
import { generateFullReport } from "../../../lib/report-generation.js";

export const maxDuration = 60;

// Accepts ONLY { reportId }. Loads all data from DB. Uses atomic RPC claim.
// If claim fails (webhook/another tab owns generation), returns 202 to poll.

export async function POST(request) {
  try {
    const rateCheck = await previewLimiter(request);
    if (!rateCheck.allowed) {
      return NextResponse.json({ error: rateCheck.error }, { status: 429 });
    }

    const { reportId } = await request.json();
    if (!reportId) return NextResponse.json({ error: "reportId is required" }, { status: 400 });

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    );

    const { data: report, error: dbError } = await supabase
      .from("reports").select("*").eq("report_id", reportId).single();

    if (dbError || !report) return NextResponse.json({ error: "Report not found." }, { status: 404 });
    if (report.payment_status !== "paid") return NextResponse.json({ error: "Payment required." }, { status: 403 });

    // Already complete → return existing (idempotent).
    if (report.report_status === "completed" && Array.isArray(report.sections) && report.sections.length > 5) {
      return NextResponse.json({
        reportId, summary: report.summary, sections: report.sections,
        tier: report.plan_tier || "premium",
        guidanceMonths: report.guidance_months || (report.has_12_month_guidance ? 12 : 0),
        deepDive: report.plan_tier === "master",
        generatedAt: report.created_at,
      });
    }

    if (!report.chart_data) return NextResponse.json({ error: "Chart data not available." }, { status: 400 });

    // ATOMIC CLAIM via RPC. Check `error` field (Supabase doesn't throw).
    let claimed = false;
    const { data: claimData, error: claimErr } = await supabase.rpc("claim_report_generation", { p_report_id: reportId });

    if (claimErr) {
      // RPC not available — fallback: check current state and attempt raw claim.
      if (report.report_status === "generating") {
        return NextResponse.json({ status: "generating", message: "Report is being generated. Please wait." }, { status: 202 });
      }
      const { data: rows } = await supabase
        .from("reports").update({ report_status: "generating", generation_started_at: new Date().toISOString() })
        .eq("report_id", reportId)
        .not("report_status", "in", '("generating","completed")')
        .select("report_id");
      claimed = Array.isArray(rows) && rows.length > 0;
    } else {
      claimed = !!claimData;
    }

    if (!claimed) {
      return NextResponse.json({ status: "generating", message: "Report is being generated by another process." }, { status: 202 });
    }

    const tier = ["essential", "premium", "master"].includes(report.plan_tier) ? report.plan_tier : "premium";
    const guidanceMonths = typeof report.guidance_months === "number" ? report.guidance_months : report.has_12_month_guidance ? 12 : 0;

    let reportData;
    try {
      reportData = await generateFullReport({
        name: report.name, gender: report.gender,
        dateOfBirth: report.date_of_birth, timeOfBirth: report.time_of_birth,
        placeOfBirth: report.place_of_birth, chartData: report.chart_data,
        personalQuestion: report.personal_question || "", tier, guidanceMonths,
      });
    } catch (genError) {
      await supabase.from("reports").update({ report_status: "failed" }).eq("report_id", reportId);
      return NextResponse.json({ error: genError.message || "Generation failed." }, { status: 500 });
    }

    await supabase.from("reports").update({
      summary: reportData.summary, sections: reportData.sections, report_status: "completed",
    }).eq("report_id", reportId);

    return NextResponse.json({
      reportId, summary: reportData.summary, sections: reportData.sections,
      tier, guidanceMonths, deepDive: tier === "master", generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error("Full report generation error:", error);
    return NextResponse.json({ error: "Failed to generate report." }, { status: 500 });
  }
}
