import { createClient } from "@supabase/supabase-js";
import { GoogleGenerativeAI } from "@google/generative-ai";
import nodemailer from "nodemailer";
import { NextResponse } from "next/server";

export const maxDuration = 60;

// Email schedule: when each email should be sent (hours after abandonment)
const EMAIL_SCHEDULE = [
  { emailNum: 1, afterHours: 12, psychology: "unfinished_task" },
  { emailNum: 2, afterHours: 24, psychology: "curiosity_gap" },
  { emailNum: 3, afterHours: 72, psychology: "authority" },
  { emailNum: 4, afterHours: 120, psychology: "personal_identity" },
  { emailNum: 5, afterHours: 168, psychology: "future_self" },
  { emailNum: 6, afterHours: 240, psychology: "social_proof" },
  { emailNum: 7, afterHours: 336, psychology: "loss_aversion" },
  { emailNum: 8, afterHours: 504, psychology: "hope" },
  { emailNum: 9, afterHours: 720, psychology: "commitment" },
  { emailNum: 10, afterHours: 1080, psychology: "discount" },
];

// Prompt templates for each email psychology
function getEmailPrompt(emailNum, psychology, lead) {
  const { name, summary, sections, date_of_birth, place_of_birth, personal_question } = lead;
  const chartContext = sections?.[0]?.content?.substring(0, 500) || summary || "";

  const prompts = {
    unfinished_task: `Write a short, warm follow-up email to ${name} who generated their astrology preview but didn't unlock the full report. Remind them their personalized report is waiting. Reference that it was generated using their exact birth details (${date_of_birth}, ${place_of_birth}). Keep it to 3-4 sentences. End with a soft CTA. Do NOT use fear or urgency.`,
    
    curiosity_gap: `Write an email to ${name} that creates curiosity. Their chart preview showed: "${chartContext.substring(0, 200)}". Mention that their full report contains 3 unusual planetary combinations that weren't shown in the preview. Tease ONE insight without revealing the answer. Keep it to 4-5 sentences.${personal_question ? ` They originally asked: "${personal_question}"` : ""}`,
    
    authority: `Write an educational email to ${name} about how Swiss Ephemeris calculations work and why exact birth time matters for accurate Vedic astrology. Explain briefly how their specific birth at ${place_of_birth} was geocoded to exact coordinates. Keep it informative, 4-5 sentences. Establish BhavishAI as a credible, scientific tool.`,
    
    personal_identity: `Write a personal email to ${name} that references their specific concern.${personal_question ? ` They asked: "${personal_question}". Address this directly.` : ` Based on their chart, their career/life path shows an important pattern.`} Remind them their full report has the detailed analysis. Keep it to 4-5 sentences. Be warm and specific.`,
    
    future_self: `Write an email to ${name} using "future self" psychology. Ask them to imagine looking back 6 months from now, wishing they had checked their planetary timeline earlier. Reference that their chart shows important transition periods ahead. Keep it 3-4 sentences. Inspirational, not fearful.`,
    
    social_proof: `Write an email to ${name} mentioning that thousands of personalized reports have been generated by BhavishAI. Mention the average report is 20 pages of structured analysis. Add that most users unlock their report within 2 minutes of seeing the preview. Keep it to 3-4 sentences. Build trust through numbers.`,
    
    loss_aversion: `Write an email to ${name} about their chart showing a period that requires extra attention. Do NOT say "disaster" or "danger." Instead say their chart "highlights a transition window where careful decisions may matter more than usual." Their full report maps these periods precisely. Keep it 3-4 sentences.`,
    
    hope: `Write a hopeful email to ${name}. Tell them every chart has periods of major opportunity. The question isn't IF good things will happen, but WHEN. Their full report contains the exact timing of their strongest periods. Keep it 3-4 sentences. Uplifting tone.`,
    
    commitment: `Write a short email to ${name} asking a simple question: "Are you still wondering about ${personal_question || 'your career and life path'}?" Tell them their report is still available whenever they're ready. One question, one line. Very short.`,
    
    discount: `Write a final email to ${name} offering 15% off their full report. This is a one-time offer expiring in 24 hours. Use code DESTINY15. Keep it brief — 3 sentences max. Clear CTA.`,
  };

  return `You are writing a follow-up email for BhavishAI, a Vedic astrology report service. 
${prompts[psychology]}

RULES:
- Write ONLY the email body (no subject line, no HTML tags)
- Use ${name}'s first name
- Keep it conversational, warm, not salesy
- Never claim "disaster" or "danger"
- End with a natural call-to-action pointing to bhavishai.in
- Maximum 100 words
- Do NOT include greetings like "Dear" or sign-offs like "Best regards"`;
}

function getSubjectLine(emailNum, psychology, name) {
  const subjects = {
    unfinished_task: `${name}, your report is waiting...`,
    curiosity_gap: `Something unusual in your chart`,
    authority: `How we calculated your exact planetary positions`,
    personal_identity: `About your question...`,
    future_self: `6 months from now`,
    social_proof: `Thousands have already unlocked theirs`,
    loss_aversion: `A period worth paying attention to`,
    hope: `Your strongest opportunity window`,
    commitment: `Still curious?`,
    discount: `15% off — one-time offer (24 hrs)`,
  };
  return subjects[psychology] || `Your BhavishAI report`;
}

export async function GET(request) {
  // Verify cron secret (optional security)
  const authHeader = request.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && process.env.CRON_SECRET) {
    // Allow without secret if not configured (for testing)
    if (process.env.CRON_SECRET) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
  }

  try {
    // Initialize services
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    );

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: "gemini-3.1-flash-lite" });

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    });

    // Fetch all unpaid leads with emails that haven't completed the sequence
    const { data: leads, error: fetchError } = await supabase
      .from("reports")
      .select("*")
      .eq("payment_status", "unpaid")
      .not("email", "is", null)
      .neq("email", "")
      .or("email_sequence_status.is.null,email_sequence_status.neq.completed");

    if (fetchError) {
      console.error("Failed to fetch leads:", fetchError);
      return NextResponse.json({ error: "DB fetch failed" }, { status: 500 });
    }

    if (!leads || leads.length === 0) {
      return NextResponse.json({ message: "No leads to process", sent: 0 });
    }

    let totalSent = 0;
    const results = [];

    for (const lead of leads) {
      try {
        // Skip if already paid
        if (lead.payment_status === "paid") continue;

        // Calculate hours since creation
        const createdAt = new Date(lead.created_at);
        const now = new Date();
        const hoursSinceCreation = (now - createdAt) / (1000 * 60 * 60);

        // Determine which email to send
        const emailsSent = lead.emails_sent_count || 0;
        
        // If all 10 emails sent, mark complete
        if (emailsSent >= 10) {
          await supabase
            .from("reports")
            .update({ email_sequence_status: "completed" })
            .eq("report_id", lead.report_id);
          continue;
        }

        // Check if next email is due
        const nextEmail = EMAIL_SCHEDULE[emailsSent];
        if (!nextEmail) continue;

        if (hoursSinceCreation < nextEmail.afterHours) continue;

        // Check cooldown: don't send if last email was less than 6 hours ago
        if (lead.last_email_sent_at) {
          const lastSent = new Date(lead.last_email_sent_at);
          const hoursSinceLastEmail = (now - lastSent) / (1000 * 60 * 60);
          if (hoursSinceLastEmail < 6) continue;
        }

        // Generate personalized email via Gemini
        const prompt = getEmailPrompt(nextEmail.emailNum, nextEmail.psychology, lead);
        let emailBody;
        try {
          const result = await model.generateContent(prompt);
          emailBody = result.response.text().trim();
        } catch (aiError) {
          console.error(`Gemini failed for ${lead.email}:`, aiError.message);
          continue; // Skip this lead, try next
        }

        // Build HTML email
        const subject = getSubjectLine(nextEmail.emailNum, nextEmail.psychology, lead.name);
        const reportUrl = `https://www.bhavishai.in/get-report`;
        
        const html = `
          <div style="font-family: Georgia, serif; max-width: 500px; margin: 0 auto; padding: 30px 20px; color: #333;">
            <p style="font-size: 15px; line-height: 1.7;">Hi ${lead.name.split(" ")[0]},</p>
            <p style="font-size: 15px; line-height: 1.7;">${emailBody.replace(/\n/g, "</p><p style='font-size: 15px; line-height: 1.7;'>")}</p>
            <p style="margin-top: 25px;">
              <a href="${reportUrl}" style="background: #8b5cf6; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-size: 14px;">
                View My Report →
              </a>
            </p>
            <p style="color: #9ca3af; font-size: 11px; margin-top: 30px;">
              BhavishAI | bhavishai.in<br>
              <a href="https://www.bhavishai.in/unsubscribe?email=${encodeURIComponent(lead.email)}" style="color: #9ca3af;">Unsubscribe</a>
            </p>
          </div>
        `;

        // Send email
        await transporter.sendMail({
          from: `BhavishAI <${process.env.GMAIL_USER}>`,
          to: lead.email,
          subject,
          html,
        });

        // Update DB
        await supabase
          .from("reports")
          .update({
            emails_sent_count: emailsSent + 1,
            last_email_sent_at: now.toISOString(),
            email_sequence_status: emailsSent + 1 >= 10 ? "completed" : "active",
          })
          .eq("report_id", lead.report_id);

        totalSent++;
        results.push({ email: lead.email, emailNum: nextEmail.emailNum, subject });

      } catch (leadError) {
        console.error(`Error processing lead ${lead.email}:`, leadError.message);
        continue;
      }
    }

    // Notify owner about cron run
    if (totalSent > 0 && process.env.GMAIL_USER) {
      try {
        await transporter.sendMail({
          from: `BhavishAI Cron <${process.env.GMAIL_USER}>`,
          to: process.env.GMAIL_USER,
          subject: `📧 Nurture Cron: Sent ${totalSent} emails`,
          html: `<pre>${JSON.stringify(results, null, 2)}</pre>`,
        });
      } catch {}
    }

    return NextResponse.json({
      success: true,
      processed: leads.length,
      sent: totalSent,
      results,
    });
  } catch (error) {
    console.error("Cron error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
