"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

export default function FullReport() {
  const router = useRouter();
  const [reportData, setReportData] = useState(null);
  const [userData, setUserData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const storedReport = sessionStorage.getItem("reportData");
    const storedUser = sessionStorage.getItem("userData");
    const paymentVerified = sessionStorage.getItem("paymentVerified");

    if (!storedReport || !storedUser) {
      router.push("/get-report");
      return;
    }

    if (!paymentVerified) {
      router.push("/report/preview");
      return;
    }

    setReportData(JSON.parse(storedReport));
    setUserData(JSON.parse(storedUser));
    setLoading(false);
  }, [router]);

  if (loading) {
    return (
      <>
        <Header />
        <main className="flex-1 pt-24 pb-16 flex items-center justify-center">
          <div className="text-center">
            <div className="animate-spin h-10 w-10 border-4 border-primary border-t-transparent rounded-full mx-auto mb-4"></div>
            <p className="text-muted">Loading your complete report...</p>
          </div>
        </main>
        <Footer />
      </>
    );
  }

  if (!reportData) return null;

  return (
    <>
      <Header />
      <main className="flex-1 pt-24 pb-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Success Banner */}
          <div className="bg-green-500/10 border border-green-500/30 rounded-2xl p-6 mb-8 text-center">
            <div className="text-3xl mb-2">✅</div>
            <h2 className="text-xl font-bold text-green-400 mb-1">Payment Successful!</h2>
            <p className="text-muted text-sm">
              Your complete report is ready below.
              {userData.email && " A backup copy has been sent to your email."}
            </p>
          </div>

          {/* Report Header */}
          <div className="bg-surface border border-border rounded-2xl p-8 mb-8 text-center">
            <div className="text-4xl mb-3">✨</div>
            <h1 className="text-3xl md:text-4xl font-bold mb-2">
              {userData.name}&apos;s Complete Vedic Astrology Report
            </h1>
            <p className="text-muted mb-4">
              Generated by BhavishAI | Report ID: {reportData.reportId}
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4 text-sm text-muted">
              <span>DOB: {new Date(userData.dateOfBirth).toLocaleDateString("en-IN")}</span>
              <span>Time: {userData.timeOfBirth}</span>
              <span>Place: {userData.placeOfBirth}</span>
            </div>
          </div>

          {/* Summary */}
          <div className="bg-primary/10 border border-primary/30 rounded-2xl p-6 mb-8">
            <h2 className="text-lg font-bold text-primary-light mb-2">Chart Summary</h2>
            <p className="text-muted italic leading-relaxed">{reportData.summary}</p>
          </div>

          {/* Table of Contents */}
          <div className="bg-surface border border-border rounded-2xl p-6 mb-8">
            <h2 className="text-lg font-bold mb-4">Table of Contents</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {reportData.sections.map((section, i) => (
                <a
                  key={i}
                  href={`#section-${i}`}
                  className="flex items-center gap-2 text-sm text-muted hover:text-primary-light transition-colors py-1"
                >
                  <span className="text-primary font-mono text-xs w-6">{String(i + 1).padStart(2, "0")}</span>
                  {section.title}
                </a>
              ))}
            </div>
          </div>

          {/* All Sections */}
          <div className="space-y-8">
            {reportData.sections.map((section, i) => (
              <div
                key={i}
                id={`section-${i}`}
                className="bg-surface border border-border rounded-2xl p-6 md:p-8 scroll-mt-24"
              >
                <div className="flex items-center gap-3 mb-4">
                  <span className="bg-primary/20 text-primary text-sm font-bold w-8 h-8 rounded-full flex items-center justify-center">
                    {i + 1}
                  </span>
                  <h2 className="text-xl md:text-2xl font-bold">{section.title}</h2>
                </div>
                <div className="text-muted leading-relaxed whitespace-pre-line">
                  {section.content}
                </div>
              </div>
            ))}
          </div>

          {/* Footer note */}
          <div className="mt-12 bg-surface border border-border rounded-2xl p-6 text-center">
            <p className="text-muted text-sm mb-4">
              This report was generated by BhavishAI using AI-powered Vedic astrology analysis.
              For major life decisions, please consult with qualified professionals.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4">
              <button
                onClick={() => {
                  // Create downloadable HTML file
                  const htmlContent = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${userData.name} - Vedic Astrology Report | BhavishAI</title><style>body{font-family:Georgia,serif;line-height:1.8;color:#333;max-width:800px;margin:0 auto;padding:40px 20px}h1{color:#7c3aed;text-align:center;border-bottom:3px solid #7c3aed;padding-bottom:15px}h2{color:#8b5cf6;margin-top:40px;border-bottom:1px solid #e5e7eb;padding-bottom:8px}.section{margin:25px 0;padding:20px;background:#f9fafb;border-radius:8px;border-left:4px solid #8b5cf6}.meta{text-align:center;color:#6b7280;font-size:14px;margin-bottom:30px}.summary{font-style:italic;background:#f3f4f6;padding:20px;border-radius:8px;margin:20px 0;border-left:4px solid #f59e0b}.footer{text-align:center;margin-top:50px;padding-top:20px;border-top:2px solid #e5e7eb;color:#9ca3af;font-size:12px}@media print{body{padding:20px}.section{break-inside:avoid}}</style></head><body><h1>✨ ${userData.name}'s Vedic Astrology Report</h1><div class="meta"><p>Generated by BhavishAI | Report ID: ${reportData.reportId}</p><p>DOB: ${new Date(userData.dateOfBirth).toLocaleDateString('en-IN')} | Time: ${userData.timeOfBirth} | Place: ${userData.placeOfBirth}</p></div><div class="summary"><strong>Chart Summary:</strong> ${reportData.summary}</div>${reportData.sections.map((s, i) => `<div class="section"><h2>${i + 1}. ${s.title}</h2><p>${s.content.replace(/\n/g, '<br>')}</p></div>`).join('')}<div class="footer"><p>© ${new Date().getFullYear()} BhavishAI | bhavishai.in</p><p>Generated using AI-powered Vedic astrology analysis. For entertainment purposes.</p></div></body></html>`;
                  
                  const blob = new Blob([htmlContent], { type: 'text/html' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = `${userData.name.replace(/\s+/g, '_')}_BhavishAI_Report.html`;
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
                  URL.revokeObjectURL(url);
                }}
                className="bg-primary hover:bg-primary-dark text-white px-6 py-3 rounded-full text-sm font-medium transition-all glow-hover"
              >
                📥 Download Report
              </button>
              <button
                onClick={() => window.print()}
                className="bg-surface-light hover:bg-border text-foreground px-6 py-2 rounded-full text-sm font-medium transition-all border border-border"
              >
                🖨️ Print Report
              </button>
              <a
                href="mailto:?subject=Check out BhavishAI - AI Astrology&body=I just got my Vedic astrology report from BhavishAI. Check it out: https://bhavishai.in"
                className="bg-surface-light hover:bg-border text-foreground px-6 py-2 rounded-full text-sm font-medium transition-all border border-border"
              >
                📨 Share with Friends
              </a>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
