"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import KundliChartsSection from "../../components/KundliCharts";
import GuidancePack from "../../components/GuidancePack";
import { createClient } from "../../../lib/supabase-browser";

// Master-tier deep-dive / roadmap sections get distinct styling.
// Must be strict: "Roadmap" alone can appear in the guidance pack's content.
// Master deep-dive sections always contain "Deep Dive" or "24-Month...Roadmap"
// in their title (generated by lib/deep-dive.js FOCUS_SECTIONS).
const isDeepDiveSectionTitle = (title) => {
  if (!title) return false;
  const t = title.toLowerCase();
  return (
    t.includes("deep dive") ||
    t.includes("deep-dive") ||
    /\b24[- ]month.*roadmap/i.test(title)
  );
};

export default function FullReport() {
  const router = useRouter();
  const [reportData, setReportData] = useState(null);
  const [userData, setUserData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [pending, setPending] = useState(false);
  const [user, setUser] = useState(null);
  const [deepDivePending, setDeepDivePending] = useState(false);

  // Check auth state
  useEffect(() => {
    const supabase = createClient();
    supabase.auth.getUser().then(({ data: { user } }) => setUser(user));
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user ?? null);
    });
    return () => subscription.unsubscribe();
  }, []);

  const handleGoogleLogin = async () => {
    const supabase = createClient();
    await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: `${window.location.origin}/auth/callback?next=/report/full`,
      },
    });
  };

  useEffect(() => {
    // Try sessionStorage first, then localStorage backup
    let storedReport = sessionStorage.getItem("reportData");
    let storedUser = sessionStorage.getItem("userData");
    const paymentVerified = sessionStorage.getItem("paymentVerified") || localStorage.getItem("paymentVerified_backup");
    const reportPending = sessionStorage.getItem("reportPending") === "true";

    if (!storedReport) storedReport = localStorage.getItem("reportData_backup");
    if (!storedUser) storedUser = localStorage.getItem("userData_backup");

    if (!storedReport || !storedUser) {
      router.push("/get-report");
      return;
    }

    if (!paymentVerified) {
      router.push("/report/preview");
      return;
    }

    setReportData(JSON.parse(storedReport));
    setUserData(JSON.parse(storedUser));
    setPending(reportPending);
    setLoading(false);
  }, [router]);

  // Master tier: the concern-specific deep-dive is generated as a separate job
  // and appended server-side. If it's pending, poll the (idempotent) endpoint
  // until the deep-dive sections appear, then hydrate them into the report.
  useEffect(() => {
    if (!reportData?.reportId) return;
    const flag = sessionStorage.getItem("masterDeepDivePending") === "true";
    const hasDeep = (reportData.sections || []).some((s) => isDeepDiveSectionTitle(s.title));
    if (!flag || hasDeep) {
      if (hasDeep) sessionStorage.removeItem("masterDeepDivePending");
      return;
    }

    setDeepDivePending(true);
    let cancelled = false;
    let attempts = 0;

    const poll = async () => {
      attempts++;
      try {
        const res = await fetch("/api/generate-master-deep-dive", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ reportId: reportData.reportId }),
        });
        const data = await res.json();
        if (!cancelled && Array.isArray(data.sections) && data.sections.some((s) => isDeepDiveSectionTitle(s.title))) {
          setReportData((prev) => {
            const updated = { ...prev, sections: data.sections };
            try { sessionStorage.setItem("reportData", JSON.stringify(updated)); } catch {}
            return updated;
          });
          sessionStorage.removeItem("masterDeepDivePending");
          setDeepDivePending(false);
          return;
        }
      } catch {
        /* ignore, will retry */
      }
      if (!cancelled && attempts < 8) {
        setTimeout(poll, 12000);
      } else {
        setDeepDivePending(false);
      }
    };

    const t = setTimeout(poll, 4000);
    return () => {
      cancelled = true;
      clearTimeout(t);
    };
  }, [reportData?.reportId]);

  if (loading) {
    return (
      <>
        <Header />
        <main className="flex-1 pt-24 pb-16 flex items-center justify-center">
          <div className="text-center">
            <div className="animate-spin h-10 w-10 border-4 border-primary border-t-transparent rounded-full mx-auto mb-4"></div>
            <p className="text-muted">Loading your complete report...</p>
          </div>
        </main>
        <Footer />
      </>
    );
  }

  if (!reportData) return null;

  // Report failed the quality check — payment succeeded but the full report
  // isn't ready. Show an honest "being prepared" screen instead of a partial one.
  if (pending) {
    return (
      <>
        <Header />
        <main className="flex-1 pt-24 pb-16 flex items-center justify-center">
          <div className="max-w-lg mx-auto px-6 text-center">
            <div className="text-4xl mb-4">✅</div>
            <h1 className="text-2xl font-bold text-green-400 mb-3">Payment Successful</h1>
            <div className="bg-surface border border-border rounded-2xl p-6 text-left">
              <p className="text-foreground leading-relaxed mb-3">
                Thank you, {userData.name}. Your personalised report is being prepared
                and will be {userData.email ? <>emailed to <strong>{userData.email}</strong></> : "sent to you"} shortly,
                after our final quality checks.
              </p>
              <p className="text-muted text-sm leading-relaxed">
                Our system double-checks every report for completeness before delivery, so this can take a few extra minutes.
                Your payment is confirmed{" "}
                <span className="font-mono text-xs">(Report ID: {reportData.reportId})</span>.
                If you don&apos;t receive it within a few hours, just reply to your confirmation email and we&apos;ll sort it out immediately.
              </p>
            </div>
          </div>
        </main>
        <Footer />
      </>
    );
  }

  // Detect the ₹149 "12-Month Personal Guidance Pack" section (only present when
  // the add-on was purchased). Used to give the buyer a distinct on-screen experience.
  const isGuidanceSection = (title) => /guidance pack|12-month|12 month/i.test(title || "");
  const guidanceIndex = (reportData.sections || []).findIndex((s) => isGuidanceSection(s.title));
  const hasGuidance = guidanceIndex >= 0;
  // Where to insert the "sign in to save" CTA. Premium/Master have 20+ sections
  // (insert after #20); Essential has ~11 (insert after its last section).
  const totalSections = (reportData.sections || []).length;
  const ctaAfterIndex = totalSections >= 20 ? 19 : Math.max(0, totalSections - 1);

  return (
    <>
      <Header />
      <main className="flex-1 pt-24 pb-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Success Banner */}
          <div className="bg-green-500/10 border border-green-500/30 rounded-2xl p-6 mb-8 text-center">
            <div className="text-3xl mb-2">✅</div>
            <h2 className="text-xl font-bold text-green-400 mb-1">Payment Successful!</h2>
            <p className="text-muted text-sm">
              Your complete report is ready below.
              {userData.email && " A backup copy has been sent to your email."}
            </p>
          </div>

          {/* Master deep-dive being prepared (separate job still running) */}
          {deepDivePending && (
            <div className="bg-accent/10 border border-accent/30 rounded-2xl p-5 mb-8 flex items-center gap-3">
              <div className="animate-spin h-5 w-5 border-2 border-accent border-t-transparent rounded-full shrink-0" />
              <p className="text-sm text-foreground">
                Your specialized <strong className="text-accent">deep-dive &amp; 24-month roadmap</strong> is being
                prepared and will appear here in a moment — no need to refresh.
              </p>
            </div>
          )}

          {/* 12-Month Guidance Pack — buyer callout. Only shows when the ₹149 add-on was purchased. */}
          {hasGuidance && (
            <a
              href={`#section-${guidanceIndex}`}
              className="block bg-gradient-to-br from-blue-500/15 via-primary/10 to-transparent border border-blue-400/30 rounded-2xl p-6 mb-8 hover:border-blue-400/60 transition-colors group"
            >
              <div className="flex items-start gap-4">
                <div className="text-3xl shrink-0">📅</div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <h2 className="text-lg font-bold text-blue-300">Your 12-Month Guidance Pack is included</h2>
                    <span className="text-[10px] uppercase tracking-wider bg-blue-500/20 text-blue-300 px-2 py-0.5 rounded-full font-semibold">₹149 add-on</span>
                  </div>
                  <p className="text-muted text-sm leading-relaxed">
                    A dedicated month-by-month guide for the next 12 months — best months, caution periods,
                    key timing windows and a practical monthly action plan for your career, money, relationships and health.
                  </p>
                  <span className="inline-flex items-center gap-1 mt-3 text-sm font-medium text-blue-300 group-hover:gap-2 transition-all">
                    Jump to your guidance pack
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" /></svg>
                  </span>
                </div>
              </div>
            </a>
          )}

          {/* Report Header */}
          <div className="bg-surface border border-border rounded-2xl p-8 mb-8 text-center">
            <div className="text-4xl mb-3">✨</div>
            <h1 className="text-3xl md:text-4xl font-bold mb-2">
              {userData.name}&apos;s Complete Vedic Astrology Report
            </h1>
            <p className="text-muted mb-4">
              Generated by BhavishAI | Report ID: {reportData.reportId}
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4 text-sm text-muted">
              <span>DOB: {new Date(userData.dateOfBirth).toLocaleDateString("en-IN")}</span>
              <span>Time: {userData.timeOfBirth}</span>
              <span>Place: {userData.placeOfBirth}</span>
            </div>
          </div>

          {/* Summary */}
          <div className="bg-primary/10 border border-primary/30 rounded-2xl p-6 mb-8">
            <h2 className="text-lg font-bold text-primary-light mb-2">Chart Summary</h2>
            <p className="text-muted italic leading-relaxed">{reportData.summary}</p>
          </div>

          {/* Kundli Charts, Planet Table, Lucky Factors, Upay */}
          {reportData.chartData && (
            <KundliChartsSection chartData={reportData.chartData} />
          )}

          {/* Table of Contents */}
          <div className="bg-surface border border-border rounded-2xl p-6 mb-8">
            <h2 className="text-lg font-bold mb-4">Table of Contents</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {reportData.sections.map((section, i) => {
                const guide = isGuidanceSection(section.title);
                return (
                  <a
                    key={i}
                    href={`#section-${i}`}
                    className={`flex items-center gap-2 text-sm transition-colors py-1 ${guide ? "text-blue-300 hover:text-blue-200 font-medium" : "text-muted hover:text-primary-light"}`}
                  >
                    <span className={`font-mono text-xs w-6 ${guide ? "text-blue-400" : "text-primary"}`}>{String(i + 1).padStart(2, "0")}</span>
                    {section.title.replace(/^\d+\.\s*/, "")}
                    {guide && <span className="text-[9px] uppercase tracking-wider bg-blue-500/20 text-blue-300 px-1.5 py-0.5 rounded-full font-semibold">📅 Guidance</span>}
                  </a>
                );
              })}
            </div>
          </div>

          {/* All Sections */}
          <div className="space-y-8">
            {reportData.sections.map((section, i) => {
              const sectionEl = isGuidanceSection(section.title) ? (
                <div key={i} id={`section-${i}`} className="scroll-mt-24">
                  <GuidancePack title={section.title} content={section.content} />
                </div>
              ) : (
                (() => {
                  const deep = isDeepDiveSectionTitle(section.title);
                  return (
                    <div
                      key={i}
                      id={`section-${i}`}
                      className={`rounded-2xl p-6 md:p-8 scroll-mt-24 border ${
                        deep ? "bg-accent/5 border-accent/40" : "bg-surface border-border"
                      }`}
                    >
                      {deep && (
                        <span className="inline-block mb-3 text-[10px] uppercase tracking-wider bg-accent/20 text-accent px-2 py-0.5 rounded-full font-semibold">
                          ★ Master Deep-Dive
                        </span>
                      )}
                      <div className="flex items-center gap-3 mb-4">
                        <span className={`text-sm font-bold w-8 h-8 rounded-full flex items-center justify-center ${
                          deep ? "bg-accent/20 text-accent" : "bg-primary/20 text-primary"
                        }`}>
                          {i + 1}
                        </span>
                        <h2 className="text-xl md:text-2xl font-bold">{section.title.replace(/^\d+\.\s*/, "")}</h2>
                      </div>
                      <div className="text-muted leading-relaxed whitespace-pre-line">
                        {section.content}
                      </div>
                    </div>
                  );
                })()
              );

              // Insert login CTA after the core report — only if not logged in
              if (i === ctaAfterIndex && !user) {
                return (
                  <div key={`section-group-${i}`}>
                    {sectionEl}
                    <div className="bg-gradient-to-br from-primary/15 via-purple-500/10 to-transparent border border-primary/30 rounded-2xl p-6 md:p-8 text-center">
                      <div className="max-w-md mx-auto">
                        <div className="text-3xl mb-3">🔐</div>
                        <h3 className="text-lg md:text-xl font-bold text-foreground mb-2">Save Your Report — Sign In Now</h3>
                        <p className="text-muted text-sm leading-relaxed mb-5">
                          This is your personalized Vedic astrology report. Sign in with Google to <strong className="text-foreground">permanently save it to your account</strong>. You&apos;ll be able to access this report from your dashboard — anywhere in the world, on any device, anytime.
                        </p>
                        <button
                          onClick={handleGoogleLogin}
                          className="inline-flex items-center gap-3 bg-white text-gray-800 px-6 py-3 rounded-full font-semibold text-sm hover:bg-gray-100 transition-all shadow-lg shadow-white/10"
                        >
                          <svg className="w-5 h-5" viewBox="0 0 24 24">
                            <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                            <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                            <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                            <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
                          </svg>
                          Sign in with Google to Save Report
                        </button>
                        <p className="text-muted/60 text-xs mt-3">Takes 2 seconds • Your report will be saved to your personal dashboard</p>
                      </div>
                    </div>
                  </div>
                );
              }

              return sectionEl;
            })}
          </div>

          {/* Footer note */}
          <div className="mt-12 bg-surface border border-border rounded-2xl p-6 text-center">
            <p className="text-muted text-sm mb-4">
              This report was generated by BhavishAI using AI-powered Vedic astrology analysis.
              For major life decisions, please consult with qualified professionals.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4">
              <button
                onClick={async () => {
                  // Server-side PDF generation (primary) with client-side fallback.
                  // Previously this was client-only using jsPDF — if the browser
                  // crashed mid-generation or the tab was closed, the PDF was lost.
                  // Now we hit the server endpoint first, which produces an identical
                  // PDF and is also what gets emailed to the customer.
                  try {
                    const res = await fetch("/api/generate-pdf", {
                      method: "POST",
                      headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({
                        name: userData.name,
                        dateOfBirth: userData.dateOfBirth,
                        timeOfBirth: userData.timeOfBirth,
                        placeOfBirth: userData.placeOfBirth,
                        reportId: reportData.reportId,
                        summary: reportData.summary,
                        sections: reportData.sections,
                        chartData: reportData.chartData,
                      }),
                    });

                    if (res.ok) {
                      const { pdf } = await res.json();
                      if (pdf) {
                        // Convert base64 to blob and trigger download
                        const byteChars = atob(pdf);
                        const byteNumbers = new Array(byteChars.length);
                        for (let i = 0; i < byteChars.length; i++) {
                          byteNumbers[i] = byteChars.charCodeAt(i);
                        }
                        const byteArray = new Uint8Array(byteNumbers);
                        const blob = new Blob([byteArray], { type: "application/pdf" });
                        const url = URL.createObjectURL(blob);
                        const a = document.createElement("a");
                        a.href = url;
                        a.download = `${userData.name.replace(/\s+/g, "_")}_BhavishAI_Report.pdf`;
                        document.body.appendChild(a);
                        a.click();
                        document.body.removeChild(a);
                        URL.revokeObjectURL(url);
                        return; // Success — skip fallback
                      }
                    }
                    throw new Error("Server PDF failed");
                  } catch (serverErr) {
                    // Fallback: client-side jsPDF (same logic the server uses)
                    console.warn("Server PDF failed, using client-side fallback:", serverErr.message);
                    const { jsPDF } = await import("jspdf");
                    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
                    const pageWidth = doc.internal.pageSize.getWidth();
                    const pageHeight = doc.internal.pageSize.getHeight();
                    const margin = 20;
                    const contentWidth = pageWidth - margin * 2;
                    let y = margin;
                    const checkPage = (needed = 20) => {
                      if (y + needed > pageHeight - margin) { doc.addPage(); y = margin; }
                    };

                    // Title page
                    doc.setFillColor(26, 26, 46);
                    doc.rect(0, 0, pageWidth, pageHeight, "F");
                    doc.setTextColor(167, 139, 250);
                    doc.setFontSize(28);
                    doc.text("BhavishAI", pageWidth / 2, 50, { align: "center" });
                    doc.setFontSize(12);
                    doc.setTextColor(200, 200, 200);
                    doc.text("AI-Powered Vedic Astrology Report", pageWidth / 2, 62, { align: "center" });
                    doc.setFontSize(22);
                    doc.setTextColor(255, 255, 255);
                    doc.text(userData.name, pageWidth / 2, 100, { align: "center" });
                    doc.setFontSize(11);
                    doc.setTextColor(180, 180, 180);
                    doc.text(`Date of Birth: ${new Date(userData.dateOfBirth).toLocaleDateString("en-IN")}`, pageWidth / 2, 115, { align: "center" });
                    doc.text(`Time: ${userData.timeOfBirth} | Place: ${userData.placeOfBirth}`, pageWidth / 2, 123, { align: "center" });
                    doc.text(`Report ID: ${reportData.reportId}`, pageWidth / 2, 135, { align: "center" });
                    doc.setTextColor(167, 139, 250);
                    doc.setFontSize(10);
                    doc.text("bhavishai.in", pageWidth / 2, pageHeight - 20, { align: "center" });

                    // Summary page
                    doc.addPage();
                    y = margin;
                    doc.setFillColor(255, 255, 255);
                    doc.rect(0, 0, pageWidth, pageHeight, "F");
                    doc.setTextColor(124, 58, 237);
                    doc.setFontSize(16);
                    doc.text("Chart Summary", margin, y);
                    y += 10;
                    doc.setTextColor(80, 80, 80);
                    doc.setFontSize(11);
                    const summaryLines = doc.splitTextToSize(reportData.summary, contentWidth);
                    doc.text(summaryLines, margin, y);
                    y += summaryLines.length * 6 + 15;

                    // Sections
                    reportData.sections.forEach((section, i) => {
                      checkPage(40);
                      doc.setFillColor(245, 245, 255);
                      doc.roundedRect(margin - 2, y - 4, contentWidth + 4, 12, 2, 2, "F");
                      doc.setTextColor(124, 58, 237);
                      doc.setFontSize(13);
                      doc.text(`${i + 1}. ${section.title.replace(/^\d+\.\s*/, "")}`, margin, y + 4);
                      y += 16;
                      doc.setTextColor(60, 60, 60);
                      doc.setFontSize(10);
                      const lines = doc.splitTextToSize(section.content, contentWidth);
                      lines.forEach((line) => { checkPage(7); doc.text(line, margin, y); y += 5.5; });
                      y += 10;
                    });

                    checkPage(20);
                    doc.setTextColor(150, 150, 150);
                    doc.setFontSize(8);
                    doc.text("Generated by BhavishAI | bhavishai.in | Powered by Swiss Ephemeris calculations.", pageWidth / 2, pageHeight - 10, { align: "center" });
                    doc.save(`${userData.name.replace(/\s+/g, "_")}_BhavishAI_Report.pdf`);
                  }
                }}
                className="bg-primary hover:bg-primary-dark text-white px-6 py-3 rounded-full text-sm font-medium transition-all glow-hover"
              >
                📥 Download PDF
              </button>
              <button
                onClick={() => window.print()}
                className="bg-surface-light hover:bg-border text-foreground px-6 py-2 rounded-full text-sm font-medium transition-all border border-border"
              >
                🖨️ Print Report
              </button>
              <a
                href="mailto:?subject=Check out BhavishAI - AI Astrology&body=I just got my Vedic astrology report from BhavishAI. Check it out: https://www.bhavishai.in"
                className="bg-surface-light hover:bg-border text-foreground px-6 py-2 rounded-full text-sm font-medium transition-all border border-border"
              >
                📨 Share with Friends
              </a>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
