import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
  title: "My Reports - Dashboard",
  description: "View all your past Vedic astrology reports generated by BhavishAI.",
};

export default async function Dashboard() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    {
      cookies: {
        getAll() { return cookieStore.getAll(); },
        setAll(cookiesToSet) {
          try { cookiesToSet.forEach(({ name, value, options }) => cookieStore.set(name, value, options)); } catch {}
        },
      },
    }
  );

  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    redirect("/");
  }

  // Get all reports for this user (paid ones)
  const { data: reports } = await supabase
    .from("reports")
    .select("*")
    .eq("user_id", user.id)
    .in("payment_status", ["paid", "founder"])
    .order("created_at", { ascending: false });

  // Is this user a Founder Member? (any of their reports has is_founder_member)
  const isFounder = Array.isArray(reports) && reports.some((r) => r.is_founder_member);

  return (
    <>
      <Header />
      <main className="flex-1 pt-24 pb-16">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold">My Reports</h1>
              <p className="text-muted mt-1">Welcome back, {user.user_metadata?.full_name || user.email}</p>
            </div>
            <Link
              href="/get-report"
              className="bg-primary hover:bg-primary-dark text-white px-6 py-3 rounded-full text-sm font-medium transition-all"
            >
              + New Report
            </Link>
          </div>

          {/* Founder Member banner */}
          {isFounder && (
            <div className="relative overflow-hidden bg-gradient-to-br from-accent/15 via-accent/5 to-transparent border-2 border-accent/40 rounded-2xl p-6 mb-8">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="text-4xl">🎖️</div>
                  <div>
                    <h2 className="text-xl font-bold text-accent">Founding Member</h2>
                    <p className="text-muted text-sm mt-1">You have <strong className="text-foreground">free unlimited reports</strong>. Generate a new report for yourself, family, or friends — no charge.</p>
                  </div>
                </div>
                <Link
                  href="/founder/new"
                  className="shrink-0 bg-accent hover:bg-accent-light text-black px-6 py-3 rounded-full text-sm font-semibold transition-all"
                >
                  🎁 Generate Free Report
                </Link>
              </div>
            </div>
          )}

          {/* Reports Grid */}
          {!reports || reports.length === 0 ? (
            <div className="bg-surface border border-border rounded-2xl p-12 text-center">
              <div className="text-5xl mb-4">📜</div>
              <h2 className="text-xl font-bold mb-2">No Reports Yet</h2>
              <p className="text-muted mb-6">
                Generate your first Vedic astrology report to see it here.
              </p>
              <Link
                href="/get-report"
                className="inline-block bg-primary hover:bg-primary-dark text-white px-8 py-3 rounded-full font-medium transition-all"
              >
                Generate My Report
              </Link>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {reports.map((report) => (
                <div
                  key={report.id}
                  className="bg-surface border border-border rounded-2xl p-6 card-hover"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <h3 className="text-lg font-bold">{report.name}</h3>
                      <p className="text-muted text-sm">{report.report_id}</p>
                    </div>
                    <span className="bg-green-500/20 text-green-400 text-xs font-bold px-2 py-1 rounded-full">
                      Paid
                    </span>
                  </div>

                  <div className="space-y-1 text-sm text-muted mb-4">
                    <p>DOB: {new Date(report.date_of_birth).toLocaleDateString("en-IN")}</p>
                    <p>Time: {report.time_of_birth} | Place: {report.place_of_birth}</p>
                    <p>Generated: {new Date(report.created_at).toLocaleDateString("en-IN")}</p>
                  </div>

                  {report.summary && (
                    <p className="text-muted text-sm italic line-clamp-2 mb-4">
                      &ldquo;{report.summary}&rdquo;
                    </p>
                  )}

                  <Link
                    href={`/dashboard/report/${report.report_id}`}
                    className="inline-block bg-primary/20 hover:bg-primary/30 text-primary-light px-4 py-2 rounded-full text-sm font-medium transition-all"
                  >
                    View Full Report →
                  </Link>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>
      <Footer />
    </>
  );
}
